# Generated by Django 2.1.9 on 2019-06-25 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='slug',
        ),
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('BUSINESS', 'Business'), ('TECHNOLOGY', 'Technology'), ('SPORT', 'Sport'), ('POLITICS', 'Politics'), ('OTHER', 'other')], default='BUSINESS', max_length=30),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
